/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}", // if using /src
  ],
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "on-secondary-container": "#a7b6cc",
        "on-primary-fixed-variant": "#004c69",
        "tertiary-fixed-dim": "#bdc2ff",
        "on-tertiary-fixed": "#000767",
        "surface-container-highest": "#2d3449",
        "primary-container": "#38bdf8",
        "on-background": "#dae2fd",
        "surface-container": "#171f33",
        "tertiary-fixed": "#e0e0ff",
        "surface-container-low": "#131b2e",
        "outline-variant": "#3e484f",
        "on-secondary-fixed": "#0d1c2d",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#222a3d",
        "on-primary-container": "#004965",
        "inverse-primary": "#00668a",
        "on-secondary": "#233143",
        "inverse-on-surface": "#283044",
        "surface-container-lowest": "#060e20",
        "on-primary-fixed": "#001e2c",
        "primary-fixed": "#c4e7ff",
        "on-secondary-fixed-variant": "#39485a",
        "error-container": "#93000a",
        outline: "#87929a",
        "on-surface-variant": "#bdc8d1",
        background: "#0b1326",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#2f3aa3",
        primary: "#8ed5ff",
        "on-tertiary-container": "#2c37a0",
        "on-primary": "#00354a",
        "secondary-container": "#39485a",
        "secondary-fixed-dim": "#b9c8de",
        "primary-fixed-dim": "#7bd0ff",
        "surface-dim": "#0b1326",
        "inverse-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "on-tertiary": "#131e8c",
        secondary: "#b9c8de",
        surface: "#0b1326",
        "surface-bright": "#31394d",
        tertiary: "#c5c9ff",
        "surface-tint": "#7bd0ff",
        "tertiary-container": "#a3abff",
        "secondary-fixed": "#d4e4fa",
        "on-surface": "#dae2fd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ['"Space Grotesk"', "sans-serif"],
        body: ['"Inter"', "sans-serif"],
        label: ['"Inter"', "sans-serif"],
      },
    },
  },
  plugins: [],
};
